### ISSUE TITLE
Deploy tagged imagestream

### ISSUE THREAD

**Issue by kaimago** [openshift/openshift-restclient-java#144]
Hi,

i like to deploy a tagged imagestream into a different project.

Commandline is working fine: oc new-app development/testtag

With the restclient api i try to make this:

        ImageStreamImportCapability cap = new ImageStreamImportCapability(project, getiClient());
        DockerImageURI image = new DockerImageURI("testtag");
        IImageStreamImport imported = cap.importImageMetadata(image);

But for this rest call:
https://..../oapi/v1/namespaces/../projectname/imagestreamimports
I get a 403 expection, despite I use the same user as commandline.

I also wondering about the request:

https://...../oapi/v1/namespaces/projectname/
**imagestreamimports**/..

commandline request is like this:

https://...../oapi/v1/namespaces/projectname/
**imagestreamimages**/..

**Comment by jcantrill** [comment]
I'm not really sure what you are trying to accomplish here.  'oc new-app' is for deploying an image to openshift which should create a service, deploymentconfig, imagestream, and possibly a buildconfig.  This is essentially the command for "create all the resources needed to support my application on openshift".  The ImageStreamImportCapability is equivalent to 'oc import-image' and is used to to seed the internal registry with images and metadata for an imagestream from a docker registry.  Can you please provide additional details.

**Comment by kaimago** [comment]
I try to adapt this blog:
https://blog.openshift.com/promoting-applications-across-environments/

--tag imagestream in project development
--deploy this tagged imagestream into a new project 

oc new-app development/myapp:promote

how can I solve this with the openshift-restclient-java ?

**Comment by jcantrill** [comment]
The openshift-restclient-java does not have feature parity with the 'oc binary'.  Many of the commands available by 'oc' are written in the client binary and are not replicated in the java client.  In order to enable similar functionality in the Jboss Tools (https://github.com/jbosstools/jbosstools-openshift), we have had to duplicate it, though even that is not exactly the same.  There is an effort to move many of these operations server-side so all client implementations can benefit but it hasn't happened yet.  In the mean time, the only  way to reproduce 'new-app' is to increase the loglevel of the oc binary, inspect the REST calls, and deduce what is happening.

**Comment by kaimago** [comment]
ok, thanks for the info.
is there any schedule about moving missing operations to the client implementation ?

**Comment by jcantrill** [comment]
@kaimago no schedule at this time
