### ISSUE TITLE
How to create new app based on existing template

### ISSUE THREAD

**Issue by vnugent** [openshift/openshift-restclient-java#209]
I was hoping the Java API would somewhat resemble the `oc` cli but it doesn't. 

In particular how would one create a new app based on existing template? eg  `oc new-app -template my-java-app`

**Comment by jcantrill** [comment]
Many of the functions and commands provided by 'oc' are baked into the client instead of residing server-side meaning LOTS of code and process duplication.  'new-app' especially does a lot of black magic to achieve the outcome you see from it.  This client attempts to primarily provide support so you can do similar things with a little effort and using some of the known endpoints that are available.  Currently, it is primarily used in jbosstools and an example of using templates can be found here: https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/job/CreateApplicationFromTemplateJob.java#L63

Please feel free to make a code contribution; we gladly accept input from the community.

**Comment by jcantrill** [comment]
Closing.  Please re-open if there are additional questions.
