### ISSUE TITLE
New ResourceKind: Node

### ISSUE THREAD

**Issue by phmaes** [openshift/openshift-restclient-java#323]
Hello guys,

is there any reason to the fact that the resource Node isn't represented in the model (INode)?
Or maybe this resource is part of another one? If yes, which one?

Thanks for the job.

Regards,

Philip

**Comment by jcantrill** [comment]
Only the fact because resources were created based on what was required for use in the openshift eclipse plugin.  Pull requests are welcome.  We should really be generating the model classes but we aren't quite there yet.  Please consider opening a PR.  Alternatively you may be interested in trying the fabric8 client library
