### ISSUE TITLE
Question: I've your project building on gradle

### ISSUE THREAD

**Issue by Tanemahuta** [openshift/openshift-restclient-java#336]
Would you like a PR which builds the project with gradle?

**Comment by adietish** [comment]
I tend to agree with @jeffmaury since our resources are very very limited. I guess that having this in a separate project, that we link to here might help attract other parties?

**Comment by Tanemahuta** [comment]
Guys, why not using TravisCI free services? - This project is Open-Source, right?

**Comment by jcantrill** [comment]
@adietish We could use Travis for CI instead of the jobs defined by the Openshift team but we would lose (I think?) the /merge and /test command features.  I don't know how important that is.  Travis would never allow us to stand up the integration tests but I defer to you your preferences.

**Comment by Tanemahuta** [comment]
I can tell you, that we have used wiremock successfully to easily setup a record-/playback based integration-test pattern. Also, travis ci supports docker, thus if you could provide a minimal kubernetes/openshift master image to boot, you could even issue the e2e-tests you are currently invoking. Just a suggestion.

**Comment by adietish** [comment]
Travis sounds fine, like it, actually. But then, one needs to maintain it, too. And that's where we lack resources. I dont really mind loosing the commands tbh. 
So in that sense I'd perfer to have this available additionally ex. in a different repo and we'd then link to it in a prominent place here. Sounds reasonable?

**Comment by adietish** [comment]
@jcantrill a file maybe, yes, but the whole build, wherever it's located or configured, needs to be watched, reacted upon, adapted, etc. And that's the point I fear since we already dont get along with all the works that to be done. Wrong?

**Comment by jcantrill** [comment]
@adietish I'm not sure I follow your concerns.  It looks like we already have travis [1] so the advantage now of the Openshift build CI is moot IMO.  It provides no added value since:

* it doesnt run integration tests
* this repo does not rely on any generated api classes.
* we dont need to rely on any automated merge functionality
* we dont rely on any automated publish functionality

Currently, I see the maintenance as low using travis.

In regards to establishing a job for the CI tests, that may be more challenging as I don't believe we have an origin docker image that is an all-in-one openshift that is easily stood up. It is something needed for a really long time but has never been addressed.

@Tanemahuta I don't see this project moving to gradle for the reasons mentioned previously but also because I believe our downstream productization has limited support for gradle.  I'm interested, however, what is the advantage of gradle over using maven; I have not followed the current trends.

[1] https://github.com/openshift/openshift-restclient-java/blob/master/.travis.yml

**Comment by adietish** [comment]
@jcantrill i didnt look deeper into this, but assuming you're right, my concerns are adressed, I won't oppose the move.
And then adressing ITs and gradle,  I dont see this happening soon either, because of the concerns mentioned above.
