### ISSUE TITLE
Issue #479 should be reopened.

### ISSUE THREAD

**Issue by welcor** [openshift/openshift-restclient-java#483]
#479 discusses whether commons-compress is in use at all. If not, it should be removed from dependencies. Otherwise, it should be bumped

**Comment by adietish** [comment]
Hi @welcor 

Unfortunately there is no active developement for this library since at least 2y now. 
If you require a great client that's in active developement, please consider moving to https://github.com/fabric8io/kubernetes-client.
You can of course take over this client here if it holds value to you. I'd transfer all permissions to you if you want to do so.

**Comment by welcor** [comment]
Thanks for the feedback. We'll move on to fabric8io
